/student/tests.c: |
    // CTester template

    #include <stdlib.h>
    #include "student_code.h"
    #include "CTester/CTester.h"

    /*
     * Generate a file named "file.txt".
     * The content is the integers in range [0, n[
     * The sum of integers in the file is returned.
     */
    int gen_file(int n){
        int fd = open("file.txt",O_WRONLY|O_CREAT|O_TRUNC, S_IRUSR|S_IWUSR);
        if(fd == -1) {
            CU_FAIL(_("Error, can not initialise test file"));
        }
        int array[n];
        int i = 0;
        int sum = 0;
        for (i = 0; i < n; i++){
            array[i]=i;
            sum+=i;
            if (write(fd, (void *) &array[i], sizeof(int)) == -1){
                CU_FAIL(_("Error, can not initialise test file"));
            }
        }
        if (close(fd) == -1)
            CU_FAIL(_("Error, can not initialise test file"));
        return sum;
    }

    void test_open() {
        set_test_metadata("q1", _("Test open"), 1);
        system("rm file.txt"); //Be sure the file does not exist
        int ret = 0;
        int tag_open = 0;
        //Test with open fail
        monitored.open = true;
        failures.open = FAIL_FIRST;
        failures.open_ret = -1;

        SANDBOX_BEGIN;
        ret = myfunc("file.txt");
        SANDBOX_END;

        if (ret != -1){
            push_info_msg(_("When there is no file, your code does not return -1."));
            CU_FAIL();
            tag_open++;
        }

        //Test if open() return a correct file descriptor.
        gen_file(13);
        monitored.open = true;
        SANDBOX_BEGIN;
        myfunc("file.txt");
        SANDBOX_END;

        if(stats.open.last_return <= 2){
            push_info_msg(_("When the open() should be fine, your code returns -1."));
            CU_FAIL();
            tag_open++;
        }
        if(tag_open == 0){
            set_tag("open");
        }
    }

    void test_no_integer() {
        set_test_metadata("q1", _("Test without any integers."), 1);
        int sum = gen_file(0); //Empty file
        int ret = 0;

        SANDBOX_BEGIN;
        ret = myfunc("file.txt");
        SANDBOX_END;

        if (ret != sum){
            push_info_msg(_("When the file does not contain any integers, your code does not return 0."));
            CU_FAIL();
        }
    }

    void test_some_integers() {
        set_test_metadata("q1", _("Test with some integers."), 1);
        int sum = gen_file(15);
        int ret = 0;

        SANDBOX_BEGIN;
        ret = myfunc("file.txt");
        SANDBOX_END;

        if (ret != sum){
            push_info_msg(_("When the file contains some integers, your code does not return the correct sum."));
            CU_FAIL();
        }
    }

    void test_some_integers_fail_read() {
        set_test_metadata("q1", _("Test with some integers (read() fail)"), 1);
        gen_file(8);
        int ret = 0;

        monitored.read = true;
        failures.read = FAIL_THIRD;
        failures.read_ret = -1;

        SANDBOX_BEGIN;
        ret = myfunc("file.txt");
        SANDBOX_END;

        if (ret != -1){
            push_info_msg(_("When a read() fails, your code does not return -1."));
            set_tag("failure_handling");
            CU_FAIL();
        }
    }

    void test_close() {
        set_test_metadata("q1", _("Test close()."), 1);
        gen_file(2);

        monitored.close = true;
        monitored.open = true;
        SANDBOX_BEGIN;
        myfunc("file.txt");
        SANDBOX_END;

        int close_ok = 0;
        if (stats.close.called == 0){
            push_info_msg(_("You did not close() the file."));
            close_ok++;
            CU_FAIL();
        }if(stats.open.last_return != stats.close.last_params.fd){
            push_info_msg(_("The close() does not close the file you opened before."));
            close_ok++;
            CU_FAIL();
        }if(close_ok == 0){
            set_tag("close");
        }
    }

    int main(int argc,char** argv){
        BAN_FUNCS();
        RUN(test_open, test_no_integer, test_some_integers, test_some_integers_fail_read, test_close);
    }
accessible: true
author: Olivier Martin
context: |-
    Given a file containing some (possibly none) positive integers (``int``), write a code that computes the sum of all integers present in the file. The sum have to be returned.

    If an error occurs, return ``-1``.
environment: cpp
evaluate: best
groups: false
limits:
    time: '30'
    output: '2'
    memory: '100'
name: '[S5] File integers reading'
network_grading: false
order: 25
problems:
    q1:
        type: code
        name: Write your code here
        header: |-
            .. code-block:: java

                /*
                 * @pre filename != NULL, name of the file
                 * @post return the sum of all integers present in the file, -1 if an error occurs.
                 */
                int sum_file(char* filename)
        language: c
stored_submissions: 0
submission_limit:
    amount: -1
    period: -1
tags:
    '0':
        name: Close
        type: 0
        visible: true
        description: This tag validate that your close are correctly performed.
        id: close
    '1':
        type: 0
        visible: true
        name: Open
        description: This tag validate you are able to open a file and handle errors
            with open().
        id: open
    '2':
        description: You do not manage failures properly during write operations.
        id: failure_handling
        visible: true
        type: 1
        name: Failure handling
    '3':
        name: Banned functions
        type: 1
        description: You use some banned functions.
        id: banned_funcs
        visible: false
    '4':
        visible: true
        description: Your code produced a double free.
        type: 1
        id: double_free
        name: Double free
    '5':
        id: sigfpe
        name: Floating Point Exception
        type: 1
        description: ''
        visible: true
    '6':
        id: memory
        type: 1
        description: ''
        name: Memory Exceeded
        visible: true
    '7':
        description: You code do not compile.
        id: not_compile
        name: Not compile
        visible: true
        type: 1
    '8':
        name: Segmentation Fault
        id: sigsegv
        type: 1
        description: ''
        visible: true
    '9':
        id: timeout
        description: Your code exceeds the maximum allowed time.
        visible: true
        type: 1
        name: Timeout
    '10':
        visible: true
        type: 2
        description: ''
        name: S5
        id: ''
    '11':
        name: File
        type: 2
        visible: true
        description: ''
        id: ''
weight: 1.0
